server:
  port: 7001
eureka:
  instance:
    hostname: ${EUREKA-DOMAIN:eureka01}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:

      defaultZone: http://eureka02:7002/eureka/,http://eureka03:7003/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000