server:
  port: 8888

spring:
  application:
    name: spring-cloud-zuul-gateway   #为这个服务取名

eureka:
  client:
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/
  instance:
    instance-id: zuul.com
    prefer-ip-address: true

info:
  app.name: spring-cloud-zuul-gateway
  company.name: www.tyg.finchina.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  routes:
    dept:
      serviceId: spring-cloud-provider       #匹配dept.path 作为区分
      path: /api/**                          #自定义访问路径，支持通配符
  ignored-services: spring-cloud-*              #需要隐藏的服务名，可以使用通配符，配置之后通过这个微服务名访问就失效了   "*" 代表的是过滤所有带服务名称的请求
  prefix: /pre                           #设置统一公共前缀，设置后访问路径：http://zuul.com:8888/prex/api/dept/3