server:
  port: 7002
eureka:
  instance:
    hostname: ${EUREKA-DOMAIN:eureka02}
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己
    fetch-registry: false           #false表示自己就是注册中心，职责是维护实例，不参加检索
    service-url:
        #设置eureka server的交互地址，即对外暴露的地址
        defaultZone: http://eureka01:7001/eureka/,http://eureka03:7003/eureka/
        server:
              enable-self-preservation: false #是否开启自我保护模式
              eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）